# Generated by Django 5.0.3 on 2024-04-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='expensetype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expense_crud.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incometype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expense_crud.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
