# Generated by Django 5.0.3 on 2024-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_crud', '0002_remove_expense_currency_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
