# Generated by Django 5.0.3 on 2024-05-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_crud', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
